baseURL = 'https://zealous-dubinsky-9431de.netlify.app/'
languageCode = 'en-us'
title = 'Hugo WebSite'
theme = 'm10c'


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Introduction"
    name = "Introduction"
    url = "/posts/introduction/"
    weight = 2
  [[menu.main]]
    identifier = "Professional experience"
    name = "Professional experience"
    url = "/posts/professionalexperience/"
    weight = 3
  [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/posts/contact/"
    weight = 3




[params]
  author = "Hugo Pires"
  description = "This my tiny website. You will find some information about me. Enjoy!"
  avatar = '/IMG_0092.jpg'


  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/hugopi/gopisite/tree/master"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/hugo-pires-160ab4194?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BZGry0Pj8T4uotMq36ddeRA%3D%3D"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/hugo_pprs/"



  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primaryColor = "#ffffff"






